### ISSUE TITLE
Unable to handle DateTime values

### ISSUE THREAD

**Issue by nkmanolovsumup** [treble37/nested_filter#3]
```
> NestedFilter.drop_by_value(%{date: DateTime.utc_now, foo: nil}, [nil]) 
** (Protocol.UndefinedError) protocol Enumerable not implemented for #<DateTime(2017-07-13T13:27:40.232574Z Etc/UTC)>
    (elixir) lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir) lib/enum.ex:116: Enumerable.reduce/3
    (elixir) lib/enum.ex:1767: Enum.reduce/3
             lib/nested_filter.ex:14: anonymous fn/3 in NestedFilter.drop_by/2
    (stdlib) lists.erl:1263: :lists.foldl/3

```

**Comment by treble37** [comment]
Thanks @nkmanolovsumup, I published 1.0.1 to hex, let me know if any issues!
